import Testing
@testable import SaysoCore

private func snapshot(_ types: Set<String>, text: String? = "hello") -> ClipboardSnapshot {
    ClipboardSnapshot(changeCount: 1, types: types, text: text, sourceApp: nil)
}

@Test func plainTextCopiesAreRecorded() {
    #expect(ClipboardPrivacy.shouldRecord(snapshot(["public.utf8-plain-text"])))
}

@Test func concealedAndTransientPasteboardItemsAreNeverRecorded() {
    #expect(!ClipboardPrivacy.shouldRecord(snapshot(["public.utf8-plain-text", "org.nspasteboard.ConcealedType"])))
    #expect(!ClipboardPrivacy.shouldRecord(snapshot(["public.utf8-plain-text", "org.nspasteboard.TransientType"])))
    #expect(!ClipboardPrivacy.shouldRecord(snapshot(["public.utf8-plain-text", "com.agilebits.onepassword"])))
}

@Test func emptyOrWhitespaceOnlyOrNonTextItemsAreSkipped() {
    #expect(!ClipboardPrivacy.shouldRecord(snapshot(["public.utf8-plain-text"], text: nil)))
    #expect(!ClipboardPrivacy.shouldRecord(snapshot(["public.utf8-plain-text"], text: "  \n\t ")))
    #expect(!ClipboardPrivacy.shouldRecord(snapshot(["public.png"], text: nil)))
}

@Test func moreMarkerTypesAreExcludedAndReportedAsSensitive() {
    for type in [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping", "com.agilebits.onepassword",
    ] {
        #expect(!ClipboardPrivacy.shouldRecord(snapshot(["public.utf8-plain-text", type])))
        #expect(ClipboardPrivacy.isSensitive(types: ["public.utf8-plain-text", type], sourceBundleID: nil))
    }
    #expect(!ClipboardPrivacy.isSensitive(types: ["public.utf8-plain-text"], sourceBundleID: nil))
}

@Test func copiesFromPasswordManagerAppsAreNeverRecordedEvenWithoutMarkers() {
    for id in ["com.1password.1password", "com.agilebits.onepassword7", "com.bitwarden.desktop", "org.keepassxc.keepassxc",
               "com.dashlane.dashlanephonefinal", "com.apple.Passwords", "com.lastpass.LastPass"] {
        let item = ClipboardSnapshot(
            changeCount: 1, types: ["public.utf8-plain-text"], text: "secret", sourceApp: "x", sourceBundleID: id
        )
        #expect(!ClipboardPrivacy.shouldRecord(item))
        #expect(ClipboardPrivacy.isSensitive(types: item.types, sourceBundleID: id))
    }
    let browser = ClipboardSnapshot(
        changeCount: 1, types: ["public.utf8-plain-text"], text: "ok", sourceApp: "Safari", sourceBundleID: "com.apple.Safari"
    )
    #expect(ClipboardPrivacy.shouldRecord(browser))
}

@Test func oversizedTextIsNotRecorded() {
    let limit = ClipboardPrivacy.maximumRecordedBytes
    #expect(limit == 262_144)
    #expect(ClipboardPrivacy.shouldRecord(snapshot(["public.utf8-plain-text"], text: String(repeating: "a", count: limit))))
    #expect(!ClipboardPrivacy.shouldRecord(snapshot(["public.utf8-plain-text"], text: String(repeating: "a", count: limit + 1))))
}
