import Foundation

/// Decides whether a pasteboard change may enter history; password-manager items never do.
public enum ClipboardPrivacy {
    /// Marker types set by password managers and by apps that flag secrets or machine-generated content.
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "com.agilebits.onepassword",
    ]
    /// Password-manager apps whose copies are skipped even when they set no marker (bundle id prefixes).
    private static let deniedAppPrefixes = [
        "com.agilebits.", "com.1password.", "com.bitwarden.", "org.keepassxc.", "com.dashlane.", "com.apple.Passwords",
        "com.lastpass.",
    ]

    /// Longest text kept, in UTF-8 bytes; larger copies are skipped so history and events stay bounded.
    public static let maximumRecordedBytes = 262_144

    public static func isSensitive(types: Set<String>, sourceBundleID: String?) -> Bool {
        if !types.isDisjoint(with: excludedTypes) { return true }
        guard let id = sourceBundleID else { return false }
        return deniedAppPrefixes.contains { id.hasPrefix($0) }
    }

    public static func shouldRecord(_ snapshot: ClipboardSnapshot) -> Bool {
        guard !isSensitive(types: snapshot.types, sourceBundleID: snapshot.sourceBundleID),
              let text = snapshot.text,
              text.utf8.count <= maximumRecordedBytes,
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return false }
        return true
    }
}
